// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$ViteReasonReact from "./App.bs.js";

import './index.css'
;

ReactDOMRe.renderToElementWithId(React.createElement(App$ViteReasonReact.make, {}), "root");

export {
  
}
/*  Not a pure module */
